name: Test project

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: actions/checkout@v7

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -GNinja
          cmake --build ./build
          cd build
          ctest
